# permissions to do viewer podhealths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podhealth-viewer-role
rules:
- apiGroups:
  - training.example.com
  resources:
  - podhealths
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - training.example.com
  resources:
  - podhealths/status
  verbs:
  - get
